import { UrgencyLevel, AppSettings } from '../types';

export const COCO_LABELS: string[] = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

export const HIGH_URGENCY_LABELS = new Set([
  'person',
  'car',
  'motorcycle',
  'bus',
  'truck',
  'bicycle',
  'dog',
  'traffic light',
  'stop sign',
  'train',
  'bear',
  'elephant',
]);

export const MEDIUM_URGENCY_LABELS = new Set([
  'chair',
  'dining table',
  'bench',
  'couch',
  'potted plant',
  'suitcase',
  'backpack',
  'sink',
  'toilet',
  'bed',
  'cat',
]);

export const VIBRATION_PATTERNS: Record<UrgencyLevel | 'obstacle', number[]> = {
  high: [0, 300, 100, 300, 100, 300],
  medium: [0, 200, 150, 200],
  low: [0, 100],
  obstacle: [0, 600, 100, 600],
};

export const URGENCY_COLORS: Record<UrgencyLevel, string> = {
  high: '#FF3B30',
  medium: '#FF9500',
  low: '#34C759',
};

export const DEFAULT_SETTINGS: AppSettings = {
  ttsEnabled: true,
  vibrationEnabled: true,
  overlayEnabled: true,
  ttsRate: 0.55,
  ttsPitch: 1.0,
  alertInterval: 3000,
  detectionThreshold: 0.5,
  selectedModel: 'yolov8n_float16.tflite',
  maxDetections: 5,
  numThreads: 4,
};
